# __Introduction to NumPy__

## __Agenda__

- Fundamentals of NumPy
  * Advantages of NumPy
  * NumPy: Installation and Import
- NumPy: Array Object
  * Creating NumPy Arrays

## __1. Fundamentals of NumPy__

NumPy (Numerical Python) is a free and open-source library that is mostly used for mathematical operations in scientific and engineering applications.

- It is a Python library used for working with arrays.
- It consists of a multidimensional array of objects and a collection of functions for manipulating them.
- It conducts mathematical and logical operations on arrays.

**Note:** The array object in NumPy is called ndarray.

### __1.1  Advantages of NumPy__
- It provides an array object that is faster than traditional Python lists.
- It provides supporting functions.
- Arrays are frequently used in data science.
- NumPy arrays are stored in one continuous place in memory unlike lists.

### __1.2 NumPy: Installation and Import__
- `C:\Users\Your Name>pip install numpy` command is used to install NumPy.
- NumPy is imported under the name np like `import numpy as np`

In [1]:
li = [1,2,3,4,5]
li[2]

3

In [2]:
type(li)

list

In [3]:
# Numpy array
! pip install numpy==2.4.0
# ! pip install numpy==2.0.1

In [4]:
import numpy as np
np.__version__

'2.4.0'

In [5]:
new_arr = np.array([1,2,3,4,5])
new_arr[0]
print(id(new_arr[0]))
print(new_arr[0])

4556806768
1


In [6]:
# Numpy array
arr0 = np.array(10) # Scalar - variable

arr1 = np.array([1,2,3,4,5]) # Vector - direction

arr2 = np.array([[1,2,3],[4,5,6]]) # Matrix - Rows and Columns

arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # Array of Matrices


print("Array 0 dim - ", arr0)
print("Dimension - ", arr0.ndim)
print("Shape - ", arr0.shape)

print("-" * 50)

print("Array 1 dim - ", arr1)
print("Dimension - ", arr1.ndim)
print("Shape - ", arr1.shape)

print("-" * 50)

print("Array 2 dim - ")
print(arr2)
print("Dimension - ", arr2.ndim)
print("Shape - ", arr2.shape)

print("-" * 50)

print("Array 3 dim - ")
print(arr3)
print("Dimension - ", arr3.ndim)
print("Shape - ", arr3.shape)


Array 0 dim -  10
Dimension -  0
Shape -  ()
--------------------------------------------------
Array 1 dim -  [1 2 3 4 5]
Dimension -  1
Shape -  (5,)
--------------------------------------------------
Array 2 dim - 
[[1 2 3]
 [4 5 6]]
Dimension -  2
Shape -  (2, 3)
--------------------------------------------------
Array 3 dim - 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension -  3
Shape -  (2, 2, 3)


In [7]:
import time
start_time = time.time()
li_million = list(range(1, 1000001))
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

Time taken: 0.007154226303100586 seconds


In [9]:
arr = np.array(li_million)
start_time = time.time()
sq_arr = arr ** 0.5
end_time = time.time()
print(f"Time taken: {end_time - start_time} seconds")

Time taken: 0.005410671234130859 seconds


## __2. NumPy: Array Object__
A NumPy ndarray object can be created by using the array() function.

In [ ]:
# Example:
import numpy as np
arr = [10,20,30,40,50]
print (arr)
print (type(arr))

[10, 20, 30, 40, 50]
<class 'list'>


In [ ]:
arr[0]

10

In [ ]:
# Example:
import numpy as np
arr = np.array([10,20,30,40,50])
print (arr)
print (type(arr))

In [ ]:
arr[0]

In [ ]:
li = [10,20.5,True,"thirty"]
li

[10, 20.5, True, 'thirty']

In [ ]:
arr = np.array([10,20.5,True,"thirty"])
print (arr)
print (type(arr))

In [ ]:
arr = np.array([10,20.5,True])
print (arr)
print (type(arr))

[10.  20.5  1. ]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([10,True])
print (arr)
print (type(arr))

In [ ]:
import time
import random
# a list of 10 million numbers randomly chosen between 1-100
li_million = random.choices(range(1,100),k=10000000)

# calculate the square root of all these numbers
start_time = time.time()

sq_li_million = [i ** 0.5 for i in li_million]

end_time = time.time()
print (end_time - start_time)

In [ ]:
# do the same with numpy array
arr = np.array(li_million)
start_time = time.time()
sq_arr = arr ** 0.5
end_time = time.time()
print (end_time - start_time)

In [ ]:
2.61026668548584 / 0.06922388076782227

### __2.1 Creating NumPy Arrays__
- Create multiple dimensional arrays, such as 0D, 1D, 2D, and 3D

In [16]:
# Create a 0D Array
arr0 = np.array(24)
print ('0D array is', arr0)
# Create a 1D Array
arr1 = np.array([1,2,3,4])
print ('1D array is', arr1)
print (arr1.shape)
# Create a 2D Array
arr2 = np.array([[1,1,1],[1,2,1]])
print ('2D array is', arr2)
print (arr2.shape)
# Create a 3D Array
arr3 = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print ('3D array is', arr3)

0D array is 24
1D array is [1 2 3 4]
(4,)
2D array is [[1 1 1]
 [1 2 1]]
(2, 3)
3D array is [[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


**Observations:**
- 1D arrays are unidimensional and have 0D arrays as its elements.
- 2D arrays have 1D arrays as their elements.
- 3D arrays have 2D arrays as their elements.

In [17]:
import numpy as np

# Zero Dimension array - Scalar
# Apply a variable in numpy
arr_0d = np.array(10)

# print
print("Array : ",arr_0d)
# Properties - Dimension
print(arr_0d.ndim)

# Properties - Shape
print(arr_0d.shape)


Array :  10
0
()


In [18]:
# 1d - array - Vector
# Replicates a list/tuple in numpy

arr_1d = np.array([10,20,30,40,50])

#print
print("Array : ",arr_1d)

# Properties - Dimension
print(arr_1d.ndim)

# Properties - Shape
print(arr_1d.shape)

Array :  [10 20 30 40 50]
1
(5,)


In [19]:
# 2 dim - Matrix
arr_2d = np.array([[10,20,30]])

#print
print(arr_2d)

# Properties - Dimension
print(arr_2d.ndim)

# Properties - Shape
print(arr_2d.shape)

[[10 20 30]]
2
(1, 3)


In [20]:
# 3d array
arr_3d = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[10,20,30]]])

#print
print(arr_3d)

# Properties - Dimension
print(arr_3d.ndim)

# Properties - Shape
print(arr_3d.shape)

[[[10 20 30]
  [40 50 60]]

 [[70 80 90]
  [10 20 30]]]
3
(2, 2, 3)


In [ ]:
# reshape the data
arr1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr1d)
# reshape to 2d
arr2d = arr1d.reshape(1,12)
print(arr2d)

In [ ]:
arr1d.shape

In [ ]:
arr2d.shape

In [ ]:
# reshape to 3d
arr3d = arr1d.reshape(2,2,3)
print(arr3d)

In [ ]:
arr3d = arr1d.reshape(2,3,2)
print(arr3d)

In [ ]:
arr3d = arr1d.reshape(6,2,1)
print(arr3d)

In [ ]:
# question - try to create a 2d matrix of 100 elements
# and then reshape to atleat 5 3d matrices

# Create a 2D matrix with 100 elements
arr_2d = np.random.randint(1, 101, size=(10, 10))
print("2D Array:")
print(arr_2d)
# Reshape into a 3D array with 5 layers
arr_3d = arr_2d.reshape(5, 5, 4)
print("\n3D Array:")
print(arr_3d)

In [ ]:
# Broadcasting

a = np.array([1,2,3,4,5])
b = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a + b)

In [ ]:
# broadcasting in column operations
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([[10],[20]])
print(a)
print(b)
print(a + b)