# __Hands-on with TensorFlow: Part A__

Let's see how TensorFlow works and build a deep neural network model using the MNIST dataset.

## Steps to be followed:
1. Import TensorFlow
2. Load the MNIST dataset
3. Create the model
4. Get predictions from the model
5. Apply softmax activation to the predictions
6. Define the loss function
7. Compile the model
8. Train the model
9. Evaluate the model
10. Create a probability model

## Step 1: Import TensorFlow

- Import TensorFlow and check its version.


In [12]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.17.0


## Step 2: Load the MNIST dataset

- Load the MNIST dataset and normalize the input data by dividing the train and test sets by 255. The pixel values of the images are divided by 255.0 to normalize them to the range [0, 1]



The MNIST dataset is a large collection of handwritten digits commonly used for training and testing in the field of machine learning. It is one of the most well-known datasets for evaluating the performance of image processing and pattern recognition algorithms.

In [14]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

__Observation:__
- The dataset has been downloaded.

## Step 3: Create the model

- Create a Sequential model with flatten, dense, and dropout layers.


In [17]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

## Step 4: Get predictions from the model

- Get the predictions from the model using the train data for one column, as the optimizer is not yet applied.


In [18]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.33908427,  1.0345942 ,  0.00268073,  0.30335724, -0.12843154,
        -0.3527338 , -0.725042  ,  0.3628366 ,  0.2245009 , -0.5176188 ]],
      dtype=float32)

__Observation:__
- An array of predicted values is displayed.

## Step 5: Apply softmax activation to the predictions

- Apply softmax activation to the predictions and print the output in terms of probabilities.


In [19]:
tf.nn.softmax(predictions).numpy()

array([[0.11769477, 0.23594634, 0.08407347, 0.1135641 , 0.07374246,
        0.05892565, 0.04060813, 0.12052376, 0.10495284, 0.04996843]],
      dtype=float32)

__Observation:__
- The predicted values in terms of probabilities are displayed as an array.

## Step 6: Define the loss function

- Create a loss function for the model.
- Define the SparseCategoricalCrossentropy loss function.


In [20]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [21]:
loss_fn(y_train[:1], predictions).numpy()

2.8314786

__Observation:__
- Here, the value is 3.46.

## Step 7: Compile the model

- Compile the model with the Adam optimizer, the loss function, and the accuracy metric.

In [23]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

__Observation:__
- Here, we have used an optimizer as Adam, loss as a loss function, and metrics as accuracy.

## Step 8: Train the model

- Fit the model using the training data for 5 epochs.


In [24]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 431us/step - accuracy: 0.8606 - loss: 0.4838
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 429us/step - accuracy: 0.9540 - loss: 0.1539
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 431us/step - accuracy: 0.9684 - loss: 0.1080
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 399us/step - accuracy: 0.9732 - loss: 0.0877
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 388us/step - accuracy: 0.9768 - loss: 0.0723


__Observations:__
- The model fits the data.
- Here, we can see that the accuracy is increased by different epochs.

## Step 9: Evaluate the model

- Evaluate the model using the testing data and print the results.


In [25]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 309us/step - accuracy: 0.9766 - loss: 0.0759


[0.07594872266054153, 0.9765999913215637]

__Observation:__

- The accuracy score is 0.979, and the loss is 0.07.

## Step 10: Create a probability model

- Create a probability model by adding the softmax layer to the existing model.



In [26]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

- Get the predictions using the test data

In [27]:
probability_model(x_test[:3])

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[9.0789399e-07, 1.0533237e-09, 2.3050014e-05, 2.9597100e-04,
        5.4566317e-11, 3.5489447e-07, 3.5977189e-13, 9.9966705e-01,
        2.7714261e-08, 1.2630246e-05],
       [1.2718401e-06, 2.9823243e-05, 9.9994445e-01, 2.1577540e-05,
        1.0091802e-14, 1.1342714e-06, 3.3809150e-07, 2.0947467e-12,
        1.4721167e-06, 6.2951214e-11],
       [5.8842824e-07, 9.9791461e-01, 4.6881929e-04, 1.2509606e-05,
        7.2965478e-05, 2.3871118e-05, 1.8990322e-05, 7.6666806e-04,
        7.1900606e-04, 1.9690460e-06]], dtype=float32)>

__Observation:__
- Here, we have the probabilities for the first three observations and different classes.