# Revision on NumPy


# Question 1: Daily Website Visitors

A startup recorded website visitors for a week.

visitors = [120, 135, 150, 110, 180, 200, 175]

### Tasks
1. Convert the list into a NumPy array.
2. Display the array and its data type.
3. Find the total number of visitors.
4. Find the average number of visitors.
5. Find the highest and lowest visitor counts.

In [4]:
import numpy as np
visitors = [120, 135, 150, 110, 180, 200, 175]

arr = np.array(visitors)
print("Array : ",arr)
print("Datatype: ",arr.dtype)
print("Total number of visitors: ",arr.sum())
print("Average number of visitors: ",arr.mean())
print("Highest number of visitors: ",arr.max())
print("Lowest number of visitors: ",arr.min())

Array :  [120 135 150 110 180 200 175]
Datatype:  int64
Total number of visitors:  1070
Average number of visitors:  152.85714285714286
Highest number of visitors:  200
Lowest number of visitors:  110


# Question 2: Student Marks Analysis

marks = [78, 85, 90, 67, 88, 92, 75]

### Tasks
1. Convert the list into a NumPy array.
2. Find the mean marks.
3. Find the median marks.
4. Find the standard deviation.
5. Count how many students scored above 80.


In [5]:
marks = [78, 85, 90, 67, 88, 92, 75]
arr = np.array(marks)
print("Mean marks: ",arr.mean())
print("Median marks: ",np.median(arr))
print("Standard deviation: ",arr.std())
print("Number of students scoring above 80: ",(arr>80).sum())

Mean marks:  82.14285714285714
Median marks:  85.0
Standard deviation:  8.441878115825233
Number of students scoring above 80:  4


# Question 3: E-Commerce Product Prices

prices = [499, 999, 1299, 699, 899]

### Tasks
1. Convert the list into a NumPy array.
2. Apply a 10% discount to all products.
3. Calculate the total revenue if one unit of each product is sold.
4. Find the most expensive product.
5. Find the cheapest product.

In [6]:
prices = [499, 999, 1299, 699, 899]
arr = np.array(prices)
print("Array: ",arr)
new_prices = arr*0.9
print("10% discount: ",new_prices)
print("Total revenue: ",new_prices.sum())
print("Most expensive product: ",arr.max())
print("Cheapest product: ",arr.min())


Array:  [ 499  999 1299  699  899]
10% discount:  [ 449.1  899.1 1169.1  629.1  809.1]
Total revenue:  3955.5
Most expensive product:  1299
Cheapest product:  499


# Question 4: Product Inventory Matrix

An electronics store has inventory counts for 12 products.

inventory = [120, 85, 95, 140, 110, 75, 60, 130, 100, 90, 150, 80]

### Tasks

1. Convert the list into a NumPy array.
2. Reshape the array into 3 rows and 4 columns.
3. Display the shape of the new array.
4. Display the first row.
5. Display the last column.
6. Find the total inventory available.

In [8]:
inventory = [120, 85, 95, 140, 110, 75, 60, 130, 100, 90, 150, 80]
arr = np.array(inventory)
print("Array: ",arr)

new_arr = arr.reshape(3,4)
print("New array: ",new_arr)
print("Shape of new array: ",new_arr.shape)

print("First row: ",new_arr[0])
print("Last column: ",new_arr[:,-1])
print("Total inventory available: ",new_arr.sum())

Array:  [120  85  95 140 110  75  60 130 100  90 150  80]
New array:  [[120  85  95 140]
 [110  75  60 130]
 [100  90 150  80]]
Shape of new array:  (3, 4)
First row:  [120  85  95 140]
Last column:  [140 130  80]
Total inventory available:  1235


# Question 5: Airline Passenger Analysis

An airline records passengers travelling over 4 days.

passengers = np.array([120, 135, 150, 180, 160, 145, 170, 190])

### Tasks

1. Display the first passenger count.
2. Display the last passenger count.
3. Display passenger counts from Day 3 to Day 6.
4. Display the first 5 values.
5. Display every alternate value.
6. Display the array in reverse order.
7. Find the highest passenger count using indexing.

In [9]:
passengers = np.array([120, 135, 150, 180, 160, 145, 170, 190])
print("First passenger count: ",passengers[0])
print("Last passenger count: ",passengers[-1])
print("Passenger counts from Day 3 to Day 6: ",passengers[2:6])
print("First 5 values: ",passengers[:5])
print("Every alternate value: ",passengers[::2])
print("Array in reverse order: ",passengers[::-1])

# sort the data on ascending terms
passengers.sort()
print("Highest passenger count: ",passengers[-1])

First passenger count:  120
Last passenger count:  190
Passenger counts from Day 3 to Day 6:  [150 180 160 145]
First 5 values:  [120 135 150 180 160]
Every alternate value:  [120 150 160 170]
Array in reverse order:  [190 170 145 160 180 150 135 120]
Highest passenger count:  190


# Question 6: Retail Store Sales Matrix


```
sales = np.array([
    [12000, 15000, 18000, 20000],
    [10000, 13000, 17000, 19000],
    [14000, 16000, 21000, 22000]
])
```



- Rows = Stores
- Columns = Months

### Tasks

1. Display sales of Store 1.
2. Display sales of Month 3 for all stores.
3. Display sales of Store 2 during Months 2 and 3.
4. Display the first two stores.
5. Display the last two months.
6. Display only the middle 2 columns.
7. Extract a sub-matrix containing:
   - Store 1 and Store 2
   - Month 2 and Month 3

In [14]:
sales = np.array([
    [12000, 15000, 18000, 20000],
    [10000, 13000, 17000, 19000],
    [14000, 16000, 21000, 22000]
])
print("Sales of Store 1: ",sales[0,:])
print("Sales of Month 3 for all stores: ",sales[:,2])
print("Sales of Store 2 during Months 2 and 3: ",sales[1,1:3])
print("First two stores: ","\n",sales[:2,:])
print("Last two months: ","\n",sales[:,-2:])
print("Middle two columns: ","\n",sales[:,1:3])
print("Sub-matrix: ","\n",sales[:2,1:3])

Sales of Store 1:  [12000 15000 18000 20000]
Sales of Month 3 for all stores:  [18000 17000 21000]
Sales of Store 2 during Months 2 and 3:  [13000 17000]
First two stores:  
 [[12000 15000 18000 20000]
 [10000 13000 17000 19000]]
Last two months:  
 [[18000 20000]
 [17000 19000]
 [21000 22000]]
Middle two columns:  
 [[15000 18000]
 [13000 17000]
 [16000 21000]]
Sub-matrix:  
 [[15000 18000]
 [13000 17000]]


# Question 7: Factory Production Dashboard


```
production = np.array([
    [100, 120, 140],
    [90, 110, 130],
    [150, 160, 180],
    [80, 100, 120]
])
```



- Rows = Machines
- Columns = Shifts

### Tasks

1. Calculate total production.
2. Calculate average production.
3. Find maximum production value.
4. Find minimum production value.
5. Calculate production by machine.
6. Calculate production by shift.
7. Find average production per machine.
8. Identify the highest-producing machine.

In [25]:
production = np.array([
    [100, 120, 140],
    [90, 110, 130],
    [150, 160, 180],
    [80, 100, 120]
])
print("Total production: ",production.sum())
print("Average production: ",production.mean())
print("Maximum production value: ",production.max())
print("Minimum production value: ",production.min())

print("Production by machine: ",production.sum(axis=1))
print("Production by shift: ",production.sum(axis=0))
print("Average production per machine: ",production.mean(axis=1))
total_production_per_machine = production.sum(axis=1)
best_machine = np.argmax(total_production_per_machine)
print("Highest-producing machine: ",best_machine + 1)

Total production:  1480
Average production:  123.33333333333333
Maximum production value:  180
Minimum production value:  80
Production by machine:  [360 330 490 300]
Production by shift:  [420 490 570]
Average production per machine:  [120.         110.         163.33333333 100.        ]
Highest-producing machine:  3


# Question 8: Employee Salary Analysis

salaries = np.array([
    25000, 32000, 45000, 38000,
    52000, 29000, 61000, 47000
])

### Tasks

1. Display salaries greater than ₹40,000.
2. Display salaries less than ₹30,000.
3. Count employees earning above ₹40,000.
4. Count employees earning below average salary.
5. Find the highest salary among employees earning above ₹40,000.
6. Create a new array containing only salaries above average.

# Question 9: Product Price Revision

prices = np.array([500, 750, 1000, 1250, 1500])

### Tasks

1. Increase all prices by ₹100.
2. Apply a 10% discount.
3. Add GST of 18%.
4. Calculate profit assuming cost price is:
   [400, 600, 800, 1000, 1200]
5. Find products with profit greater than ₹200.
6. Calculate final selling price after discount and GST.

# Question 10: Stock Market Analysis

prices = np.array([
    100, 105, 102, 108, 110,
    115, 112, 118, 120, 125
])

### Tasks

1. Calculate mean stock price.
2. Calculate median stock price.
3. Calculate standard deviation.
4. Calculate variance.
5. Find the 25th percentile.
6. Find the 75th percentile.
7. Find the range of stock prices.
8. Determine whether the stock prices show high or low volatility based on standard deviation.
9. Calculate Z-score of the highest stock price.

## Arange and Linspace

In [5]:
# 1 million records as multiples of 3
million_records = [3*x for x in range(1,1000000)]

arr = np.arange(3,3000001,3)
len(arr)

1000000

In [7]:
arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
# linspace
arr = np.linspace(1,10,3)
arr

array([ 1. ,  5.5, 10. ])

# Pandas

In [26]:
!pip install pandas

In [27]:
!pip install pandas==3.0.3

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 83.7 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.3 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.3 which is incompatible.


In [2]:
# upgrade
!pip install pandas --upgrade

In [4]:
# import pandas
import numpy as np
import pandas as pd

In [11]:
# working with Pandas Data structure

# Series

arr = np.arange(1,101)

series_data = pd.Series(arr)
print(series_data)



0       1
1       2
2       3
3       4
4       5
     ... 
95     96
96     97
97     98
98     99
99    100
Length: 100, dtype: int64


In [13]:
# first n rows
series_data.head(4)

0    1
1    2
2    3
3    4
dtype: int64

In [14]:
# last n rows
series_data.tail(4)

96     97
97     98
98     99
99    100
dtype: int64

In [18]:
# random n
series_data.sample(8)

34    35
9     10
50    51
40    41
53    54
74    75
46    47
44    45
dtype: int64

In [19]:
# shape
series_data.shape

(100,)

In [20]:
# information
series_data.info()

<class 'pandas.Series'>
RangeIndex: 100 entries, 0 to 99
Series name: None
Non-Null Count  Dtype
--------------  -----
100 non-null    int64
dtypes: int64(1)
memory usage: 932.0 bytes


In [21]:
# descriptive statistical summary
series_data.describe()

count    100.000000
mean      50.500000
std       29.011492
min        1.000000
25%       25.750000
50%       50.500000
75%       75.250000
max      100.000000
dtype: float64