In [2]:
import numpy as np
arr = np.array ([10,20,30,40,50])
print (arr)
print (type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
a1 = np.array ([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
a1.shape

(2, 5)

In [12]:
# 3D array
arr3D = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
print(arr3D)
print(arr3D.shape)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
(1, 2, 2, 3)
